//PORT LOCAL

### Get all
GET http://localhost:8080/contact

### Get Contact
GET http://localhost:8080/contact/681edf4b58dc47667c20c011

### Get Contact2
GET http://localhost:8080/contact/681ee53b58dc47667c20c015

### Get Contact3
GET http://localhost:8080/contact/681ee54558dc47667c20c016

### Add new contact
POST http://localhost:8080/contact HTTP/1.1
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "jsmith@example.com",
  "favoriteColor": "red",
  "birthday": "1990-09-15"
}

### PUT - Update contact
PUT http://localhost:8080/contact/681ee54558dc47667c20c016
Content-Type: application/json

{
  "firstName": "Lisa",
  "lastName": "Smith",
  "email": "lisa_new@example.com",
  "favoriteColor": "yellow",
  "birthday": "1990-05-10"
}

### DELETE - Delete contact
DELETE http://localhost:8080/contact/681f1cdb069a7943bafcbca4

//DEPLOY
### All contact
GET https://cse340-st3g.onrender.com/contact

### Single Cantact by ID
GET https://cse340-st3g.onrender.com/contact/681edf4b58dc47667c20c011

###
GET https://cse340-st3g.onrender.com/contact/681ee53b58dc47667c20c015

###
GET https://cse340-st3g.onrender.com/contact/681ee54558dc47667c20c016

### Add new contact
POST https://cse340-st3g.onrender.com/contact HTTP/1.1
Content-Type: application/json

{
  "firstName": "Abligal",
  "lastName": "Roger",
  "email": "john@example.com",
  "favoriteColor": "green",
  "birthday": "1990-12-12"
}

### PUT - Update contact
PUT https://cse340-st3g.onrender.com/contact/681ee54558dc47667c20c016
Content-Type: application/json

{
  "firstName": "Lisa",
  "lastName": "Smith",
  "email": "lisa_new@example.com",
  "favoriteColor": "yellow",
  "birthday": "1990-05-10"
}

### Delete contact
DELETE  https://cse340-st3g.onrender.com/contact/6826e7c914622f6f3898c1ef